### ISSUE TITLE
Markören hoppar över ett extra tecken

### ISSUE THREAD

**Issue by erikmaarten** [henriiik/vlm#1]
Kul projekt! Du kanske har sett det redan, men såg att om man backar (backspace) i insert mode från en rad till raden ovanför hamnar markören hoppar markören över det sista tecknet på raden.

**Comment by henriiik** [comment]
Hallå! Kul att du hittade hit! Hade inte koll på det och fixade. Saknas ju dock 99% av vim's features än  😅
